version: '3.9'

services:
  web-django:
    image: hendradev/equin-dj-docker
    container_name: equin-dj-c
    build: .
    volumes:
      - .:/equin-dj-docker
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  db-postgres:
    image: library/postgres:13
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  postgres_data:
