# Generated by Django 3.1.6 on 2021-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pekerjaan',
            options={'verbose_name': 'Pekerjaan', 'verbose_name_plural': 'Pekerjaan'},
        ),
        migrations.AlterModelOptions(
            name='pekerjaanpelamarkerja',
            options={'verbose_name': 'Daftar Pelamar', 'verbose_name_plural': 'Daftar Pelamar'},
        ),
        migrations.AlterModelOptions(
            name='pelamarkerja',
            options={'verbose_name': 'Pelamar Kerja', 'verbose_name_plural': 'Pelamar Kerja'},
        ),
        migrations.AlterModelOptions(
            name='pemberikerja',
            options={'verbose_name': 'Pemberi Kerja', 'verbose_name_plural': 'Pemberi Kerja'},
        ),
        migrations.AddConstraint(
            model_name='pekerjaanpelamarkerja',
            constraint=models.UniqueConstraint(fields=('id_pemberikerja_pekerjaan', 'id_pelamarkerja'), name='Pelamar tidak mungkin melamar yang sama 2x'),
        ),
    ]
